### ISSUE TITLE
Can't enable Fluent UI

### ISSUE THREAD

**Issue by chengnan049** [TheOld/vscode-fluent-ui#8]
### Information: 
>Version: 1.61.0-insider (system setup)
Commit: 87260247dc7b912db6e6a21a366e6f50dca759ba
Date: 2021-09-03T20:58:36.778Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

- [x] Looking for simliar issues on [GitHub ](https://github.com/TheOld/vscode-fluent-ui/issues)
- [x] Uninstall the software and remove the remaining files and repeat the steps
- [x] Reproduce issues with the Stable version

### How to reproduce:

1. Install vscode-insider from the [official website](https://code.visualstudio.com/insiders/).The installation directory is `D:\Program Files\Microsoft VS Code Insiders`

![image](https://user-images.githubusercontent.com/46060083/132129296-124587fb-ac2d-41ff-b6df-5d0597a7dfb0.png)

2. Open extensions page and install `Fluent UI` and then `What's New for Fluent UI` documentation will open automatically (I don't know why this document can't be opened, maybe I'm in China, but I've opened the proxy tool)

![image](https://user-images.githubusercontent.com/46060083/132129306-31088f2b-b9b4-43cf-b505-4a17c95371da.png)

![image](https://user-images.githubusercontent.com/46060083/132129312-398a4bff-7c7a-4e4b-b9aa-fd04a92088f9.png)

3. Run `Fluent UI: Enable` > a popup with `Command 'Fluent UI: Enable' resulted in an error (command 'fluent.enableEffects' not found) error (command 'fluent.enableEffects' not found)`

![image](https://user-images.githubusercontent.com/46060083/132129321-ab439232-9ccd-4ecb-8d84-81bb14289718.png)

Edited: Just edited two stupid spell mistakes🤣🤣🤣

**Comment by shanmax-code** [comment]
Same problem on VS 1.61 and 1.58 😓

**Comment by wizzymore** [comment]
Same problem for me, after installing the extension i get the same error:

![image](https://user-images.githubusercontent.com/25827787/132486402-8995ea74-6019-4f34-947c-bd83008bb795.png)

**Comment by TheOld** [comment]
Hi folks, thank you for that. I'll be looking into the issue soon.

**Comment by Aureate-Sunshine** [comment]
same problem

**Comment by TheOld** [comment]
Hi y'all. 
I've published a new version with a possible fix for this issue. 

Would you kindly test it out, please?

I don't have the Insider's version so can't test on that one at the moment. But I hope the fix will work for this version too. The What's New page seems to be the culprit, so I've removed it as it wasn't providing much anyways.

**Comment by chengnan049** [comment]
> Hi y'all.
> I've published a new version with a possible fix for this issue.
> 
> Would you kindly test it out, please?
> 
> I don't have the Insider's version so can't test on that one at the moment. But I hope the fix will work for this version too. The What's New page seems to be the culprit, so I've removed it as it wasn't providing much anyways.

The problem is solved, but a new problem has emerged
![image](https://user-images.githubusercontent.com/46060083/132781461-8fba846b-d172-4351-97fd-04e4a5385f9b.png)

**Comment by DimitrisMilonopoulos** [comment]
> > Hi y'all.
> > I've published a new version with a possible fix for this issue.
> > Would you kindly test it out, please?
> > I don't have the Insider's version so can't test on that one at the moment. But I hope the fix will work for this version too. The What's New page seems to be the culprit, so I've removed it as it wasn't providing much anyways.
> 
> The problem is solved, but a new problem has emerged
> ![image](https://user-images.githubusercontent.com/46060083/132781461-8fba846b-d172-4351-97fd-04e4a5385f9b.png)

Click on settings and Just don't show again, this is an expected behavior as you gain permission to change vscode internal files for styling.

**Comment by chengnan049** [comment]
OK

Sent from Mail for Windows<https://go.microsoft.com/fwlink/?LinkId=550986>

**Comment by pavi2410** [comment]
Still have the same problem. Using the latest versions of vscode and this extension.

**Comment by TheOld** [comment]
> Still have the same problem. Using the latest versions of vscode and this extension.

You might have leftover code from the previous version. You might be able to fix by doing this:

1. Go to the folder (Windows): `C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\electron-browser\workbench\`
2. Open the `workbench.html` file (you can use any editor if VSCode is not working at this point)
3. Delete additional `<script>` tags from the file. They should be surrounded by `Fluent-UI` comments. If not, you'll want your `workbench.html` file to look like this:

```
<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />


	</head>
	<body aria-label="">
	</body>

	<!-- Init Bootstrap Helpers -->
	<script src="../../../../bootstrap.js"></script>
	<script src="../../../../vs/loader.js"></script>
	<script src="../../../../bootstrap-window.js"></script>

	<!-- Startup via workbench.js -->
	<script src="workbench.js"></script>
</html>
```
4. Uninstall the `Fluent UI` extension.
5. Restart VSCode
6. Follow the install instructions again.

Let me know if that doesn't fix your problem.

**Comment by pavi2410** [comment]
> You might have leftover code from the previous version.

Sorry if I wasn't clear. It was my first time install.

**Comment by notAperson535** [comment]
@pavi2410 follow the instructions provided. The vscode update messed it up for me and the instructions fixed it.

**Comment by fisforfaheem** [comment]
still not fixed? why
